name: Deploy node app to production
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source 
        uses: actions/checkout@v4
      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker image
        run: docker build -t dkswnn/mernsda .
      - name: Publish Docker image
        run: docker push dkswnn/mernsda:latest    
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from DockerHub
        run: docker pull dkswnn/mernsda:latest
      - name: Stop existing container
        run: docker stop mernsda || true # Continue if container doesn't exist
      - name: Remove existing container
        run: docker rm mernsda || true # Continue if container doesn't exist
      - name: Run Docker container
        run: docker run -d -p 8000:8000 --name mernsda -e MONGO_PASSWORD='${{secrets.MONGO_PASSWORD}}' dkswnn/mernsda

